"""Reports Routes - Generate and download financial reports"""
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Literal
import json
import io

from app.core.database import get_db
from app.models.assessment import FinancialAssessment

router = APIRouter()

@router.get("/assessment/{assessment_id}")
async def generate_assessment_report(
    assessment_id: int,
    format: Literal["pdf", "excel", "json"] = Query("json", description="Report format"),
    db: Session = Depends(get_db)
):
    """
    Generate and download financial assessment report
    
    Formats:
    - json: JSON data (default)
    - pdf: PDF report (placeholder)
    - excel: Excel spreadsheet (placeholder)
    """
    # Get assessment
    assessment = db.query(FinancialAssessment).filter(
        FinancialAssessment.id == assessment_id
    ).first()
    
    if not assessment:
        raise HTTPException(status_code=404, detail="Assessment not found")
    
    # Prepare report data - use getattr with defaults for optional fields
    report_data = {
        "assessment_id": assessment.id,
        "business_name": assessment.business.business_name if assessment.business else "Unknown",
        "assessment_date": assessment.assessment_date.isoformat(),
        "overall_health_score": getattr(assessment, 'overall_health_score', 0),
        "credit_rating": getattr(assessment, 'credit_rating', 'N/A'),
        "risk_level": getattr(assessment, 'risk_level', 'unknown'),
        "liquidity_score": getattr(assessment, 'liquidity_score', 0),
        "profitability_score": getattr(assessment, 'profitability_score', 0),
        "efficiency_score": getattr(assessment, 'efficiency_score', 0),
        "ai_summary": getattr(assessment, 'ai_summary', ''),
        "strengths": getattr(assessment, 'strengths', []),
        "weaknesses": getattr(assessment, 'weaknesses', []),
        "opportunities": getattr(assessment, 'opportunities', []),
        "threats": getattr(assessment, 'threats', []),
        "cost_optimization_recommendations": getattr(assessment, 'cost_optimization_recommendations', []),
        "revenue_enhancement_recommendations": getattr(assessment, 'revenue_enhancement_recommendations', []),
        "working_capital_recommendations": getattr(assessment, 'working_capital_recommendations', []),
        "tax_optimization_recommendations": getattr(assessment, 'tax_optimization_recommendations', []),
        "recommended_products": getattr(assessment, 'recommended_products', []),
        "financial_ratios": getattr(assessment, 'financial_ratios', {}),
    }
    
    if format == "json":
        # Return JSON
        json_str = json.dumps(report_data, indent=2, default=str)
        return StreamingResponse(
            io.BytesIO(json_str.encode()),
            media_type="application/json",
            headers={
                "Content-Disposition": f"attachment; filename=financial_report_{assessment_id}.json"
            }
        )
    
    elif format == "pdf":
        # PDF generation - return as plain text for now
        pdf_content = f"""Financial Health Assessment Report

Business: {report_data['business_name']}
Date: {report_data['assessment_date']}

OVERALL SCORES
--------------
Overall Health Score: {report_data['overall_health_score']}/100
Credit Rating: {report_data['credit_rating']}
Risk Level: {report_data['risk_level']}

DETAILED SCORES
---------------
Liquidity Score: {report_data['liquidity_score']}/100
Profitability Score: {report_data['profitability_score']}/100
Efficiency Score: {report_data['efficiency_score']}/100

AI SUMMARY
----------
{report_data['ai_summary']}

STRENGTHS
---------
{chr(10).join(f"- {s}" for s in report_data['strengths'])}

WEAKNESSES
----------
{chr(10).join(f"- {w}" for w in report_data['weaknesses'])}

RECOMMENDATIONS
---------------
Cost Optimization: {len(report_data['cost_optimization_recommendations'])} items
Revenue Enhancement: {len(report_data['revenue_enhancement_recommendations'])} items
Tax Optimization: {len(report_data['tax_optimization_recommendations'])} items

---
Generated by Financial Health Assessment Tool
"""
        return StreamingResponse(
            io.BytesIO(pdf_content.encode('utf-8')),
            media_type="text/plain",
            headers={
                "Content-Disposition": f"attachment; filename=financial_report_{assessment_id}.txt"
            }
        )
    
    elif format == "excel":
        # Generate XLSX using pandas
        import pandas as pd
        
        # Create DataFrame
        data = {
            'Metric': [
                'Business',
                'Date',
                '',
                'Overall Health Score',
                'Credit Rating',
                'Risk Level',
                'Liquidity Score',
                'Profitability Score',
                'Efficiency Score'
            ],
            'Value': [
                report_data['business_name'],
                report_data['assessment_date'],
                '',
                report_data['overall_health_score'],
                report_data['credit_rating'],
                report_data['risk_level'],
                report_data['liquidity_score'],
                report_data['profitability_score'],
                report_data['efficiency_score']
            ]
        }
        
        df = pd.DataFrame(data)
        
        # Save to Excel
        excel_buffer = io.BytesIO()
        with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Financial Report')
        
        excel_buffer.seek(0)
        
        return StreamingResponse(
            excel_buffer,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={
                "Content-Disposition": f"attachment; filename=financial_report_{assessment_id}.xlsx"
            }
        )
    
    return {"error": "Invalid format"}


@router.get("/{report_id}")
async def get_report(report_id: int):
    """Get report details (placeholder)"""
    return {"message": "Get report placeholder", "report_id": report_id}
